- name: This playbook is to insatll nginx
  hosts: dev
  become: true
  tasks:
  - name: Install nginx
    ansible.builtin.yum:
      name: nginx
      state: latest
  - name: start nginx service
    ansible.builtin.service:
      name: nginx
      state: started
  
