- name: This is to call varaibles from file
  hosts: localhost
  vars_files:
   - varaibles.yaml
  tasks:
  - name: This is to print variables from the file
    ansible.builtin.debug:
      msg: " we are learning {{course}} is prepared by {{trainer}} with fees of {{fees}} and duriation of {{duration}} "

