- name: This playbook is for variable prompt
  hosts: localhost
  vars_prompt:
  - name: input
    prompt: What is your input?
    private: false
  # - name: password
  #   prompt: What is your password?
  #   private: true
  tasks:
  - name: This tasks is to display the variable prompt
    ansible.builtin.debug:
      msg: "input is: {{input}}"
