- name : This playbook is to call the varibales from all 
  hosts: dm2
  vars:
    course: devops-play
  # vars_files:
  # - variables.yaml
  vars_prompt:
  - name: input
    prompt: What is your input?
    private: false
  tasks: 
  - name: This task is to call the varaibles
    # vars:
    #   course: devops-task
    ansible.builtin.debug:
      msg: "course is : {{course}}"