- name: This playbook is to create a user roboshop if its doesnt exists
  hosts: localhost
  tasks:
  - name: check roboshop user exists or not
    ansible.builtin.command: id roboshop
    register: output 
    ignore_errors: yes
  - name: display the output
    ansible.builtin.debug: 
      msg: "output is {{output}}"
  - name: Display output with rc
    ansible.builtin.debug:
      msg: "output is {{output.rc}}"
  - name: create a user
    ansible.builtin.user:
      name: roboshop
    when: output.rc != 0