- name: This playbook is to install the packages on loop 
  hosts: localhost 
  become: true
  tasks:
  - name: This task is to install the packages
    ansible.builtin.yum:
      name : "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - { name: 'nginx', state: 'installed' }
    - { name: 'postfix', state: 'absent' }
    - { name: 'cyrus-sasl-plain', state: 'installed' }
    - { name: 'mailx', state: 'absent' }

